export const ActionTypes = Object.freeze({
  User: {
    STATUS_UPDATE: "USER/STATUS_UPDATE",
    RECEIVE_NB_OF_STORIES: "USER/RECEIVE_NB_OF_STORIES",
    RECEIVE_READLIST: "USER/RECEIVE_READLIST",
  },

  Stories: {
    RECEIVE_ALL: "STORIES/RECEIVE",
    ADD_TO_READLIST: "STORIES/ADD_TO_READLIST",
    REMOVE_FROM_READLIST: "STORIES/REMOVE_FROM_READLIST",
    INCREMENT_NB_VIEWS: "CONVERSATION/INCREMENT_NB_VIEWS",
  },

  Conversation: {
    RECEIVE: "CONVERSATION/RECEIVE",
    RESET: "CONVERSATION/RESET",
    LIKE: "CONVERSATION/LIKE",
    DISLIKE: "CONVERSATION/DISLIKE",
    CONNECTED_USER_HAS_LIKED: "CONVERSATION/CONNECTED_USER_HAS_LIKED",
  },
});
